specVersion: 0.2.0
name: acala-subql
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala-rpc-0.aca-api.network
  dictionary: https://api.subquery.network/sq/AcalaNetwork/acala-dictionary
  chaintypes:
    file: './src/types.json'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: TransferredToken
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: BurnedToken
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: BurnedTokenWithRemark
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: loans
            method: PositionUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: loans
            method: ConfiscateCollateralAndDebit
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: loans
            method: transferLoan
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: InterestRatePerSecUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: LiquidationRatioUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: LiquidationPenaltyUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: RequiredCollateralRatioUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: MaximumTotalDebitValueUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: GlobalInterestRatePerSecUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: LiquidateUnsafeCDP
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: honzon
            method: CloseLoanHasDebitByDex
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ProvisioningToEnabled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddLiquidity
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: RemoveLiquidity
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: Swap
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ListProvision
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddProvision
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: incentives
            method: DepositDexShare
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: incentives
            method: WithdrawDexShare
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: incentives
            method: PayoutRewards
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: incentives
            method: ClaimRewards
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homaLite
            method: Minted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homaLite
            method: RedeemRequestCancelled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homaLite
            method: RedeemRequested
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homaLite
            method: Redeemed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homa
            method: Minted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homa
            method: RequestedRedeem
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homa
            method: RedeemRequestCancelled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homa
            method: RedeemedByFastMatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: homa
            method: RedeemedByUnbond
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
